# This is a basic workflow to help you get started with Actions

name: Continuous Integration/Continuous Deployment

# Controls when the workflow will run
on: [push]
 
env:
  AZURE_FUNCTIONAPP_NAME: twiliocolorstackdemo  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '5.0.4'              # set this to the dotnet version to use

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
     - name: 'Checkout GitHub Action'
       uses: actions/checkout@master

     - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
       uses: actions/setup-dotnet@v1
       with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
     - name: 'Resolve Project Dependencies Using Dotnet'
       shell: pwsh
       run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
        
     - name: 'Run Azure Functions Action'
       uses: Azure/functions-action@v1
       id: fa
       with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
